apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtogo-app
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: pl0xi/auth_service:latest
          ports:
            - containerPort: 8086