name: Apache camel test

on:
  pull_request: 
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-22.04 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'  

    - name: Running tests
      working-directory: ./apache_camel   
      run: mvn clean test -q