name: Account service test

on:
  push:
    branches:
      - main  
  pull_request: 
    branches:
      - '*'
jobs:
  build:

    runs-on: ubuntu-22.04 # Possible change

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'  

    - name: Running tests
      working-directory: ./auth_service  
      run: mvn clean test -q

    - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth_service:latest
    