name: Deploy

on:
  push: 
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-22.04 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'  
      
    - name: Running restaurant service tests
      working-directory: ./restaurant_service   
      run: mvn clean test

    - name: Running integration service tests
      working-directory: ./apache_camel   
      run: mvn clean test

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push restaurant service
      uses: docker/build-push-action@v5
      with:
        context: ./restaurant_service
        file: ./restaurant_service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/restaurant_service:latest

    - name: Build and push integration service
      uses: docker/build-push-action@v5
      with:
        context: ./apache_camel
        file: ./apache_camel/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/apache_camel:latest
  